#=========================== Filebeat inputs =============================
filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      templates:
      - condition:
          equals:
            docker.container.labels.com.scrubbed.corp.khd: ""
        config:
        - type: docker
          containers.ids: '*'
          json.keys_under_root: true
          processors:
          - add_docker_metadata: ~
          - decode_json_fields:
              fields: ["message"]
      - condition:
          not:
            equals:
              docker.container.labels.com.scrubbed.corp.khd: ""
        config:
        - type: docker
          containers.ids: '*'
          json.ignore_decoding_error: true
          processors:
          - add_docker_metadata: ~

#----------------------------- Logstash output --------------------------------
output.logstash:
  hosts: ["<inserthostname>:5901"]

#================================ Logging =====================================

# Sets log level. The default log level is info.
# Available log levels are: error, warning, info, debug
logging.level: error
logging.json: true

# At debug level, you can selectively enable logging only for some components.
# To enable all selectors use ["*"]. Examples of other selectors are "beat",
# "publish", "service".
#logging.selectors: ["*"]
